name: Build for Android

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.JKS_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > filcnaplo/android/key.properties
          echo "storePassword=${{ secrets.JKS_STORE_PASSWORD }}" >> filcnaplo/android/key.properties
          echo "keyPassword=${{ secrets.JKS_KEY_PASSWORD }}" >> filcnaplo/android/key.properties
          echo "keyAlias=${{ secrets.JKS_KEY_ALIAS }}" >> filcnaplo/android/key.properties
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: "true"
      - name: Install dependencies
        run: ./fix-pub.sh
      - name: Build
        run: cd filcnaplo && ./build.sh
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: filcnaplo/build/app/outputs/flutter-apk/app-release.apk
